name       : python-cleo
version    : 0.8.1
release    : 1
source     :
    - https://pypi.io/packages/source/c/cleo/cleo-0.8.1.tar.gz : 3d0e22d30117851b45970b6c14aca4ab0b18b1b53c8af57bed13208147e4069f
license    : MIT
component  : programming.python
summary    : Cleo allows you to create beautiful and testable command-line interfaces.
description: |
    Create beautiful and testable command-line interfaces. Cleo is mostly a higher level wrapper for CliKit, so a lot of the components and utilities comes from it. Refer to its documentation for more information.
rundeps    :
    - python-clikit
build      : |
    %python3_setup
install    : |
    %python3_install
